# -*- coding: utf-8 -*-
"""Ana_Silvia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izB-rvrWPP7Fow6V848fbJbpK7IyQJn1
"""

import pandas as pd
import numpy as np
#import matplotlib.pyplot
import sqlite3
from sqlite3 import connect
#import streamlit as st

conn= connect('ecsel_database.db')

#read data from the different tables
df_project= pd.read_sql ('SELECT * FROM PROJECTS', conn)
df_participants= pd.read_sql ('SELECT * FROM PARTICIPANTS', conn)
df_countries= pd.read_sql ('SELECT * FROM COUNTRIES', conn)

#merge data from diferent tables into df2
df2= pd.read_sql ('''SELECT p.*, pj.*, c.Country FROM PARTICIPANTS AS p, PROJECTS AS pj, COUNTRIES AS c
WHERE p.projectID=pj.projectID AND p.country=c.Acronym''', conn)
df2=df2.rename(columns={'country':'Acronym'})
df2=df2.rename(columns={'acronym':'organization_acronym'})


#df2['ecContribution'] = df2['ecContribution'].astype(int)

"""Part 3:"""

country_list = df2['Country'] #selecting the country names list
country_acronyms = {'Belgium': 'BE', 'Bulgaria': 'BG', 'Czechia': 'CZ', 'Denmark': 'DK', 'Germany':
'DE', 'Estonia': 'EE', 'Ireland': 'IE','Greece': 'EL', 'Spain': 'ES', 'France': 'FR', 'Croatia':
'HR', 'Italy': 'IT', 'Cyprus': 'CY', 'Latvia': 'LV', 'Lithuania': 'LT','Luxembourg': 'LU',
'Hungary': 'HU', 'Malta': 'MT', 'Netherlands': 'NL', 'Austria': 'AT', 'Poland': 'PL', 'Portugal':
'PT','Romania': 'RO', 'Slovenia': 'SI', 'Slovakia': 'SK', 'Finland': 'FI', 'Sweden': 'SE'}
### countname = st.selectbox('Choose a Country', country_acronyms.keys()) #input by the user of the name of the country
countname = input('Choose a Country') #input by the user of the name of the country
def country_to_acronym(countname): #defining a function
  found = False #setting parameter = False, when True it is when the acronym is found.
  while found == False: #while acronym is not found
    if countname in country_acronyms.keys(): #if the country name is in the key of the dictionary
      value = country_acronyms[countname] #getting the acronym associated with the key (name of the country)
      found = True #set parameter to trye
    else:
      ### st.write("Not a country on the list, try again: ") #if the country doesn't exist in the database it will ask the user again to try again
      print("Not a country on the list, try again: ") #if the country doesn't exist in the database it will ask the user again to try again
      found = False
    return(value)

acronym_c = country_to_acronym(countname)
print('The selected country is:', acronym_c) #calling the function to display to display the acronym
### st.write('The selected country is:', acronym_c) #calling the function to display to display the acronym


### @st.cache
def display_dataframe(df2, acronym_c):
    df2 = df2[df2['Acronym'] == acronym_c]
    df2_part = df2.groupby(['name','shortName', 'activityType', 'organizationURL']).agg({'ecContribution':['sum']})
   # df2_part = df2_part.sort_values(by=('ecContribution', 'sum'), ascending= False) #sorting by sum of ecContribution in descending order
    return(df2_part)

participants = display_dataframe(df2,acronym_c)
print(participants)
### st.write(participants)

#part4: generate a new project dataframe with project coordinators from the selected country and order it in ascending order by 'shortName'
#project_coordinators_df= pd.read_sql('''SELECT p.shortName, p.name, p.activityType, pj.projectAcronym FROM PARTICIPANTS AS
#p INNER JOIN PROJECTS AS pj ON p.projectID = pj.projectID INNER JOIN COUNTRIES AS c on p.country=c.Acronym
#WHERE p.role='Coordinator' AND c.Country=? ORDER BY p.shortName ASC''', conn, params=[countname])
#print('Project coordinators from', countame)
#print(project_coordinators_df)

conn.close()
