# -*- coding: utf-8 -*-
"""intermediate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcwSDc7AjZBrNyVb_W-vdq5YyTkS-Fpc
"""

import pandas as pd
import numpy as np
#import matplotlib.pyplot
import sqlite3

from sqlite3 import connect


import streamlit as st

conn= connect('ecsel_database.db')
df_project= pd.read_sql ('SELECT * FROM PROJECTS', conn)
df_participants= pd.read_sql ('SELECT * FROM PARTICIPANTS', conn)
df_countries= pd.read_sql ('SELECT * FROM COUNTRIES', conn)
df2= pd.read_sql ('''SELECT p.*, pj.*, c.Country FROM PARTICIPANTS AS p, PROJECTS AS pj, COUNTRIES AS c
WHERE p.projectID=pj.projectID AND p.country=c.Acronym''', conn)
df2=df2.rename(columns={'country':'Acronym'})
df2=df2.rename(columns={'acronym':'organization_acronym'})
#conn.close()

"""Part 3:"""

#conn = connect('ecsel_database.db')
country_list = df2['Country']

option = st.selectbox('Choose an option', ['a','b','c'])
